#!/bin/sh

##---------- Autostart Apps ----------##

# Run Keybindings Daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Run Polybar
sh $HOME/.config/polybar/polybar.sh

# Run Dunst
dunst --config $HOME/.config/dunst/dunstrc &

# Start Wallpaper
feh --bg-max --no-fehbg --randomize ~/Pictures/Wallpaper/* &

##---------- X Settings ----------##

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Set Resolution
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 &

# Set Keyboard Repeat Delay and Rate
xset r rate 400 50

##---------- Window Rules ----------##

bspc monitor -d 1 2 3 4 5 6

bspc rule -a discord    desktop=^6 follow=on focus=on

##---------- General Configuration ----------##

bspc config border_width 5
bspc config window_gap 15
bspc config split_ratio 0.5

bspc config normal_border_color "#000000"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#00CED1"
bspc config presel_feedback_color "#fd2e59"

bspc config focus_follows_pointer true
bspc config pointer_modifier true
bspc config paddingless_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc config left_padding 50
#bspc config right_padding 50
#bspc config top_padding 50
#bspc config bottom_padding 50
